version = 0.1
[default.deploy.parameters]
stack_name = "springbootsamdeploy"
resolve_s3 = true
s3_prefix = "springbootsamdeploy"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
